window.esdocSearchIndex = [
  [
    "our-people/lib/our-people/storage/collection.js~collection",
    "class/lib/our-people/storage/collection.js~Collection.html",
    "<span>Collection</span> <span class=\"search-result-import-path\">our-people/lib/our-people/storage/collection.js</span>",
    "class"
  ],
  [
    "our-people/lib/our-people/storage/file/index.js~filestorage",
    "class/lib/our-people/storage/file/index.js~FileStorage.html",
    "<span>FileStorage</span> <span class=\"search-result-import-path\">our-people/lib/our-people/storage/file/index.js</span>",
    "class"
  ],
  [
    "our-people/lib/our-people/storage/storage-interface.js~storageinterface",
    "class/lib/our-people/storage/storage-interface.js~StorageInterface.html",
    "<span>StorageInterface</span> <span class=\"search-result-import-path\">our-people/lib/our-people/storage/storage-interface.js</span>",
    "class"
  ],
  [
    "our-people/lib/our-people/helpers/branch-name.js~branchname",
    "function/index.html#static-function-branchName",
    "<span>branchName</span> <span class=\"search-result-import-path\">our-people/lib/our-people/helpers/branch-name.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/cli/index.js~cli",
    "function/index.html#static-function-cli",
    "<span>cli</span> <span class=\"search-result-import-path\">our-people/lib/our-people/cli/index.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/storage/file-storage.js~createfilestorage",
    "function/index.html#static-function-createFileStorage",
    "<span>createFileStorage</span> <span class=\"search-result-import-path\">our-people/lib/our-people/storage/file-storage.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/storage/index.js~createstorage",
    "function/index.html#static-function-createStorage",
    "<span>createStorage</span> <span class=\"search-result-import-path\">our-people/lib/our-people/storage/index.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/validators/email.js~emailvalidator",
    "function/index.html#static-function-emailValidator",
    "<span>emailValidator</span> <span class=\"search-result-import-path\">our-people/lib/our-people/validators/email.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/questions/github.js~filter",
    "function/index.html#static-function-filter",
    "<span>filter</span> <span class=\"search-result-import-path\">our-people/lib/our-people/questions/github.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/questions/twitter.js~filter",
    "function/index.html#static-function-filter",
    "<span>filter</span> <span class=\"search-result-import-path\">our-people/lib/our-people/questions/twitter.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/config/index.js~getconfiguration",
    "function/index.html#static-function-getConfiguration",
    "<span>getConfiguration</span> <span class=\"search-result-import-path\">our-people/lib/our-people/config/index.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/questions/email-address.js~invalidatedmessage",
    "variable/index.html#static-variable-invalidatedMessage",
    "<span>invalidatedMessage</span> <span class=\"search-result-import-path\">our-people/lib/our-people/questions/email-address.js</span>",
    "variable"
  ],
  [
    "our-people/lib/our-people/questions/linkedin.js~invalidatedmessage",
    "variable/index.html#static-variable-invalidatedMessage",
    "<span>invalidatedMessage</span> <span class=\"search-result-import-path\">our-people/lib/our-people/questions/linkedin.js</span>",
    "variable"
  ],
  [
    "our-people/lib/our-people/questions/name.js~invalidatedmessage",
    "variable/index.html#static-variable-invalidatedMessage",
    "<span>invalidatedMessage</span> <span class=\"search-result-import-path\">our-people/lib/our-people/questions/name.js</span>",
    "variable"
  ],
  [
    "our-people/lib/our-people/questions/phone-number.js~invalidatedmessage",
    "variable/index.html#static-variable-invalidatedMessage",
    "<span>invalidatedMessage</span> <span class=\"search-result-import-path\">our-people/lib/our-people/questions/phone-number.js</span>",
    "variable"
  ],
  [
    "our-people/lib/our-people/validators/name.js~namevalidator",
    "function/index.html#static-function-nameValidator",
    "<span>nameValidator</span> <span class=\"search-result-import-path\">our-people/lib/our-people/validators/name.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/validators/phone-number.js~phonenumbervalidator",
    "function/index.html#static-function-phoneNumberValidator",
    "<span>phoneNumberValidator</span> <span class=\"search-result-import-path\">our-people/lib/our-people/validators/phone-number.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/questions/index.js~questionbyname",
    "function/index.html#static-function-questionByName",
    "<span>questionByName</span> <span class=\"search-result-import-path\">our-people/lib/our-people/questions/index.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/questions/index.js~questionvalidatorbyname",
    "function/index.html#static-function-questionValidatorByName",
    "<span>questionValidatorByName</span> <span class=\"search-result-import-path\">our-people/lib/our-people/questions/index.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/questions/index.js~questions",
    "variable/index.html#static-variable-questions",
    "<span>questions</span> <span class=\"search-result-import-path\">our-people/lib/our-people/questions/index.js</span>",
    "variable"
  ],
  [
    "our-people/lib/our-people/helpers/random.js~randomstring",
    "function/index.html#static-function-randomString",
    "<span>randomString</span> <span class=\"search-result-import-path\">our-people/lib/our-people/helpers/random.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/validators/url.js~urlvalidator",
    "function/index.html#static-function-urlValidator",
    "<span>urlValidator</span> <span class=\"search-result-import-path\">our-people/lib/our-people/validators/url.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/questions/email-address.js~validate",
    "function/index.html#static-function-validate",
    "<span>validate</span> <span class=\"search-result-import-path\">our-people/lib/our-people/questions/email-address.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/questions/linkedin.js~validate",
    "function/index.html#static-function-validate",
    "<span>validate</span> <span class=\"search-result-import-path\">our-people/lib/our-people/questions/linkedin.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/questions/name.js~validate",
    "function/index.html#static-function-validate",
    "<span>validate</span> <span class=\"search-result-import-path\">our-people/lib/our-people/questions/name.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/questions/phone-number.js~validate",
    "function/index.html#static-function-validate",
    "<span>validate</span> <span class=\"search-result-import-path\">our-people/lib/our-people/questions/phone-number.js</span>",
    "function"
  ],
  [
    "our-people/lib/our-people/web-api/index.js~webapi",
    "function/index.html#static-function-webApi",
    "<span>webApi</span> <span class=\"search-result-import-path\">our-people/lib/our-people/web-api/index.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/angular-ui.js",
    "file/lib/angular-ui.js.html",
    "lib/angular-ui.js",
    "file"
  ],
  [
    "lib/cli.js",
    "file/lib/cli.js.html",
    "lib/cli.js",
    "file"
  ],
  [
    "lib/index.js",
    "file/lib/index.js.html",
    "lib/index.js",
    "file"
  ],
  [
    "lib/our-people/cli/index.js",
    "file/lib/our-people/cli/index.js.html",
    "lib/our-people/cli/index.js",
    "file"
  ],
  [
    "lib/our-people/config/index.js",
    "file/lib/our-people/config/index.js.html",
    "lib/our-people/config/index.js",
    "file"
  ],
  [
    "lib/our-people/helpers/branch-name.js",
    "file/lib/our-people/helpers/branch-name.js.html",
    "lib/our-people/helpers/branch-name.js",
    "file"
  ],
  [
    "lib/our-people/helpers/random.js",
    "file/lib/our-people/helpers/random.js.html",
    "lib/our-people/helpers/random.js",
    "file"
  ],
  [
    "lib/our-people/questions/email-address.js",
    "file/lib/our-people/questions/email-address.js.html",
    "lib/our-people/questions/email-address.js",
    "file"
  ],
  [
    "lib/our-people/questions/github.js",
    "file/lib/our-people/questions/github.js.html",
    "lib/our-people/questions/github.js",
    "file"
  ],
  [
    "lib/our-people/questions/index.js",
    "file/lib/our-people/questions/index.js.html",
    "lib/our-people/questions/index.js",
    "file"
  ],
  [
    "lib/our-people/questions/linkedin.js",
    "file/lib/our-people/questions/linkedin.js.html",
    "lib/our-people/questions/linkedin.js",
    "file"
  ],
  [
    "lib/our-people/questions/name.js",
    "file/lib/our-people/questions/name.js.html",
    "lib/our-people/questions/name.js",
    "file"
  ],
  [
    "lib/our-people/questions/phone-number.js",
    "file/lib/our-people/questions/phone-number.js.html",
    "lib/our-people/questions/phone-number.js",
    "file"
  ],
  [
    "lib/our-people/questions/twitter.js",
    "file/lib/our-people/questions/twitter.js.html",
    "lib/our-people/questions/twitter.js",
    "file"
  ],
  [
    "lib/our-people/storage/collection.js",
    "file/lib/our-people/storage/collection.js.html",
    "lib/our-people/storage/collection.js",
    "file"
  ],
  [
    "lib/our-people/storage/collection.js~collection#add",
    "class/lib/our-people/storage/collection.js~Collection.html#instance-method-add",
    "lib/our-people/storage/collection.js~Collection#add",
    "method"
  ],
  [
    "lib/our-people/storage/collection.js~collection#all",
    "class/lib/our-people/storage/collection.js~Collection.html#instance-method-all",
    "lib/our-people/storage/collection.js~Collection#all",
    "method"
  ],
  [
    "lib/our-people/storage/collection.js~collection#collection",
    "class/lib/our-people/storage/collection.js~Collection.html#instance-member-collection",
    "lib/our-people/storage/collection.js~Collection#collection",
    "member"
  ],
  [
    "lib/our-people/storage/collection.js~collection#constructor",
    "class/lib/our-people/storage/collection.js~Collection.html#instance-constructor-constructor",
    "lib/our-people/storage/collection.js~Collection#constructor",
    "method"
  ],
  [
    "lib/our-people/storage/collection.js~collection#drop",
    "class/lib/our-people/storage/collection.js~Collection.html#instance-method-drop",
    "lib/our-people/storage/collection.js~Collection#drop",
    "method"
  ],
  [
    "lib/our-people/storage/collection.js~collection#ready",
    "class/lib/our-people/storage/collection.js~Collection.html#instance-method-ready",
    "lib/our-people/storage/collection.js~Collection#ready",
    "method"
  ],
  [
    "lib/our-people/storage/collection.js~collection#remove",
    "class/lib/our-people/storage/collection.js~Collection.html#instance-method-remove",
    "lib/our-people/storage/collection.js~Collection#remove",
    "method"
  ],
  [
    "lib/our-people/storage/collection.js~collection#store",
    "class/lib/our-people/storage/collection.js~Collection.html#instance-member-store",
    "lib/our-people/storage/collection.js~Collection#store",
    "member"
  ],
  [
    "lib/our-people/storage/file-storage.js",
    "file/lib/our-people/storage/file-storage.js.html",
    "lib/our-people/storage/file-storage.js",
    "file"
  ],
  [
    "lib/our-people/storage/file/example.js",
    "file/lib/our-people/storage/file/example.js.html",
    "lib/our-people/storage/file/example.js",
    "file"
  ],
  [
    "lib/our-people/storage/file/index.js",
    "file/lib/our-people/storage/file/index.js.html",
    "lib/our-people/storage/file/index.js",
    "file"
  ],
  [
    "lib/our-people/storage/file/index.js~filestorage#add",
    "class/lib/our-people/storage/file/index.js~FileStorage.html#instance-method-add",
    "lib/our-people/storage/file/index.js~FileStorage#add",
    "method"
  ],
  [
    "lib/our-people/storage/file/index.js~filestorage#all",
    "class/lib/our-people/storage/file/index.js~FileStorage.html#instance-method-all",
    "lib/our-people/storage/file/index.js~FileStorage#all",
    "method"
  ],
  [
    "lib/our-people/storage/file/index.js~filestorage#cachedready",
    "class/lib/our-people/storage/file/index.js~FileStorage.html#instance-member-cachedReady",
    "lib/our-people/storage/file/index.js~FileStorage#cachedReady",
    "member"
  ],
  [
    "lib/our-people/storage/file/index.js~filestorage#constructor",
    "class/lib/our-people/storage/file/index.js~FileStorage.html#instance-constructor-constructor",
    "lib/our-people/storage/file/index.js~FileStorage#constructor",
    "method"
  ],
  [
    "lib/our-people/storage/file/index.js~filestorage#drop",
    "class/lib/our-people/storage/file/index.js~FileStorage.html#instance-method-drop",
    "lib/our-people/storage/file/index.js~FileStorage#drop",
    "method"
  ],
  [
    "lib/our-people/storage/file/index.js~filestorage#path",
    "class/lib/our-people/storage/file/index.js~FileStorage.html#instance-member-path",
    "lib/our-people/storage/file/index.js~FileStorage#path",
    "member"
  ],
  [
    "lib/our-people/storage/file/index.js~filestorage#ready",
    "class/lib/our-people/storage/file/index.js~FileStorage.html#instance-method-ready",
    "lib/our-people/storage/file/index.js~FileStorage#ready",
    "method"
  ],
  [
    "lib/our-people/storage/file/index.js~filestorage#remove",
    "class/lib/our-people/storage/file/index.js~FileStorage.html#instance-method-remove",
    "lib/our-people/storage/file/index.js~FileStorage#remove",
    "method"
  ],
  [
    "lib/our-people/storage/index.js",
    "file/lib/our-people/storage/index.js.html",
    "lib/our-people/storage/index.js",
    "file"
  ],
  [
    "lib/our-people/storage/storage-interface.js",
    "file/lib/our-people/storage/storage-interface.js.html",
    "lib/our-people/storage/storage-interface.js",
    "file"
  ],
  [
    "lib/our-people/validators/email.js",
    "file/lib/our-people/validators/email.js.html",
    "lib/our-people/validators/email.js",
    "file"
  ],
  [
    "lib/our-people/validators/name.js",
    "file/lib/our-people/validators/name.js.html",
    "lib/our-people/validators/name.js",
    "file"
  ],
  [
    "lib/our-people/validators/phone-number.js",
    "file/lib/our-people/validators/phone-number.js.html",
    "lib/our-people/validators/phone-number.js",
    "file"
  ],
  [
    "lib/our-people/validators/url.js",
    "file/lib/our-people/validators/url.js.html",
    "lib/our-people/validators/url.js",
    "file"
  ],
  [
    "lib/our-people/web-api/index.js",
    "file/lib/our-people/web-api/index.js.html",
    "lib/our-people/web-api/index.js",
    "file"
  ],
  [
    "lib/web-api.js",
    "file/lib/web-api.js.html",
    "lib/web-api.js",
    "file"
  ]
]